language: node_js
node_js:
- '0.11'

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: hatfield.love
  local-dir: dist
  detect_encoding: true
  acl: public_read
  skip_cleanup: true
  cache_control: "max-age=86400"
  expires: "2012-12-21 00:00:00 -0000"
